lab4/Controllers/MedicineController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using lab4.Data;
using lab4.Models;
using lab4.ViewModels;
using lab4.Filters;
using Newtonsoft.Json;

namespace lab4.Controllers
{
    [CatchExceptionFilter]
    public class MedicineController : Controller
    {
        private int pageSize = 5;
        private Context db;
        private Medicine _medicine = new Medicine
        {
            MedicineName = "",
            MedicineIndications = "",
            MedicineContraindications = "",
            MedicineManufacturer = "",
            MedicinePackaging = "",
            MedicineDosage = ""
        };

        public MedicineController(Context medicineContext) {
            db = medicineContext;
        }

        [HttpGet]
        public IActionResult Index(SortState sortOrder = SortState.No, int index = 0)
        {
            Medicine sessionMedicines = HttpContext.Session.GetObject<Medicine>("Medicines");
            string sessionSortState = HttpContext.Session.GetString("SortState");
            int? page = HttpContext.Session.GetInt32("Page");
            if (page == null)
            {
                page = 0;
                HttpContext.Session.SetInt32("Page", 0);
            }
            else
            {
                if (!(page < 1 && index < 0))
                    page += index;
                HttpContext.Session.SetInt32("Page", (int)page);
            }

            if (sessionMedicines != null)
            {
                _medicine = sessionMedicines;
            }

            if (sessionSortState != null)
                if (sortOrder == SortState.No)
                    sortOrder = (SortState)Enum.Parse(typeof(SortState), sessionSortState);

            ViewData["NameSort"] = sortOrder == SortState.NameDesc ? SortState.NameAsc : SortState.NameDesc;

            HttpContext.Session.SetString("SortState", sortOrder.ToString());
            IQueryable<Medicine> medicine = Sort(db.Medicines, sortOrder,
                _medicine.MedicineName, (int)page);
            MedicinesViewModel medicinesView = new MedicinesViewModel
            {
                MedicineViewModel = _medicine,
                PageViewModel = medicine,
                PageNumber = (int)page
            };

            return View(medicinesView);
        }

        [HttpPost]
        public IActionResult Index(Medicine medicine)
        {
            var sessionSortState = HttpContext.Session.GetString("SortState");
            SortState sortOrder = new SortState();
            if (sessionSortState != null)
                sortOrder = (SortState)Enum.Parse(typeof(SortState), sessionSortState);

            int? page = HttpContext.Session.GetInt32("Page");
            if (page == null)
            {
                page = 0;
                HttpContext.Session.SetInt32("Page", 0);
            }

            IQueryable<Medicine> medicines = Sort(db.Medicines, sortOrder,
                medicine.MedicineName, (int)page);
            HttpContext.Session.SetObject("Medicines", medicine);

            MedicinesViewModel medicinesView = new MedicinesViewModel
            {
                MedicineViewModel = medicine,
                PageViewModel = medicines,
                PageNumber = (int)page
            };

            return View(medicinesView);
        }

        private IQueryable<Medicine> Sort(IQueryable<Medicine> medicines,
            SortState sortOrder, string name, int page)
        {
            switch (sortOrder)
            {
                case SortState.NameAsc:
                    medicines = medicines.OrderBy(s => s.MedicineName);
                    break;
                case SortState.NameDesc:
                    medicines = medicines.OrderByDescending(s => s.MedicineName);
                    break;
            }
            medicines = medicines.Where(o => o.MedicineName.Contains(name ?? "")).Skip(page * pageSize).Take(pageSize);
            return medicines;
        }

        private void SetSessionMedicines(string sessionMedicines) {
            _medicine.MedicineName = sessionMedicines.Split(':')[0];
        }
    }
}

lab4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab4</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        form div {
            padding: 10px;
            width: 400px;
            text-align: right;
        }
        form {
            padding: 10px;
        }

        div {
            padding: 0px 10px 10px 10px;
        }

        input[type=text] {
            width: 200px;
        }

        input[type=date] {
            width: 200px;
        }

        select {
            width: 200px;
        }

        table {
            border: 1px solid black;
            width: 260px;
            padding: 0px 10px 0px 10px;
        }
        .views {
            width: 500px;
        }
        tr {
            border: 1px solid black;
        }
        td {
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1Test</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicine" asp-action="Index">Medicine</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Disease" asp-action="Index">Disease</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Treatment" asp-action="Index">Treatment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Patient</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - lab4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>